/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Config {
  paddingX: number
  paddingY: number
  maxWidth: number
  maxHeight: number
  scale: Array<number>
  scaleSuffix: Array<string>
}

/** Packs textures found in `source` using `config`. Outputs to `dest` with `name` as the start of the filename. */
export declare function packTextures(source: string, dest: string, name: string, config: Config): void
