/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Config {
  paddingX: number
  paddingY: number
  maxWidth: number
  maxHeight: number
  scale: Array<number>
  scaleSuffix: Array<string>
}

export declare function hello(source: string, dest: string, name: string, config: Config): void
